
#当前环境开发环境dev
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blctek?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password:

engineer:
  deviceUrl: http://172.16.0.95:8890
